version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Setup Scarb
          command: |
            wget https://github.com/software-mansion/scarb/releases/download/$SCARB_VERSION/scarb-$SCARB_VERSION-x86_64-unknown-linux-gnu.tar.gz
            tar -xvzf scarb-$SCARB_VERSION-x86_64-unknown-linux-gnu.tar.gz
            echo 'export PATH="$PATH:$CIRCLE_WORKING_DIRECTORY/scarb-$SCARB_VERSION-x86_64-unknown-linux-gnu/bin"' >> "$BASH_ENV"
      - run: scarb build
    environment:
      SCARB_VERSION: v0.1.0

workflows:
  build:
    jobs:
      - build
