name: Build Scarb project

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "0.5.2"
      - run: scarb build
      - run: scarb test
