name: CI
on:
  push:
  merge_group:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@be0d6b396aaf744ab41b2ecc00dcdaeb8d93e759
      - run: tree .
      - name: Scarb build
        run: scarb build
